### ISSUE TITLE
Travis setting in rules/src/main/scala/.travis.yml

### ISSUE THREAD

**Issue by nwtgck** [xuwei-k/replace-symbol-literals#2]
Hi, I have a question.
I found the following Travis setting in a subdirectory. Is this meaningful? I'm not sure Travis CI supports subdirectory configuration.
https://github.com/xuwei-k/replace-symbol-literals/blob/e7ae4e7789766f368538001e10da285d101d9a99/rules/src/main/scala/.travis.yml#L1-L6

**Comment by xuwei-k** [comment]
fixed. thanks!
